FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Install debugger with proper permissions
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        curl \
        procps \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg \
    && chmod +x /vsdbg/vsdbg

COPY . .
RUN dotnet restore

ENV ASPNETCORE_ENVIRONMENT=Development
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/ever-pal-firebase-adminsdk-fbsvc.json
ENV ASPNETCORE_URLS=https://+:5001

ENTRYPOINT ["dotnet", "run", "--no-launch-profile"]
