namespace EverPal.WebApi.Localization;

public static class PdfStrings
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["en"] = new()
        {
            ["health_report_title"] = "{0}'s Health Report",
            ["health_report_subtitle"] = "Pet Health Tracking Report",
            ["pet_profile"] = "Pet Profile",
            ["name"] = "Name:",
            ["breed"] = "Breed:",
            ["age"] = "Age:",
            ["age_years"] = "{0} years",
            ["weight"] = "Weight:",
            ["report_period"] = "Report Period:",
            ["no_entries"] = "No entries",
            ["total_entries"] = "Total Entries:",
            ["generated"] = "Generated:",
            ["medical_disclaimer_title"] = "Medical Disclaimer",
            ["medical_disclaimer_text"] = "This document contains health observations recorded by the pet owner. It is NOT a veterinary medical record or diagnosis. Please consult with a licensed veterinarian for medical advice regarding your pet's health.",
            ["health_timeline"] = "Health Timeline",
            ["no_health_entries"] = "No health entries found for this period.",
            ["tags"] = "Tags: ",
            ["page"] = "Page ",
            ["of"] = " of ",
            ["generated_by"] = "Generated by EverPal",
            ["log_type_symptom"] = "Symptom",
            ["log_type_food"] = "Food",
            ["log_type_medication"] = "Medication",
            ["log_type_vet_visit"] = "Vet Visit",
            ["log_type_weight"] = "Weight",
            ["log_type_general"] = "General",
            ["log_type_stool"] = "Stool",
            ["log_type_urine"] = "Urine",
            ["log_type_vomit"] = "Vomit"
        },
        ["pl"] = new()
        {
            ["health_report_title"] = "Raport zdrowia - {0}",
            ["health_report_subtitle"] = "Raport monitorowania zdrowia zwierzaka",
            ["pet_profile"] = "Profil zwierzaka",
            ["name"] = "Imie:",
            ["breed"] = "Rasa:",
            ["age"] = "Wiek:",
            ["age_years"] = "{0} lat",
            ["weight"] = "Waga:",
            ["report_period"] = "Okres raportu:",
            ["no_entries"] = "Brak wpisow",
            ["total_entries"] = "Liczba wpisow:",
            ["generated"] = "Wygenerowano:",
            ["medical_disclaimer_title"] = "Zastrzezenie medyczne",
            ["medical_disclaimer_text"] = "Niniejszy dokument zawiera obserwacje zdrowotne zarejestrowane przez wlasciciela zwierzecia. NIE JEST to dokumentacja medyczna ani diagnoza weterynaryjna. W sprawach dotyczacych zdrowia Twojego zwierzecia prosimy o konsultacje z uprawnionym lekarzem weterynarii.",
            ["health_timeline"] = "Historia zdrowia",
            ["no_health_entries"] = "Nie znaleziono wpisow zdrowotnych dla tego okresu.",
            ["tags"] = "Tagi: ",
            ["page"] = "Strona ",
            ["of"] = " z ",
            ["generated_by"] = "Wygenerowano przez EverPal",
            ["log_type_symptom"] = "Objaw",
            ["log_type_food"] = "Jedzenie",
            ["log_type_medication"] = "Leki",
            ["log_type_vet_visit"] = "Wizyta u weterynarza",
            ["log_type_weight"] = "Waga",
            ["log_type_general"] = "Ogolne",
            ["log_type_stool"] = "Stolec",
            ["log_type_urine"] = "Mocz",
            ["log_type_vomit"] = "Wymioty"
        }
    };

    public static string Get(string language, string key)
    {
        var lang = language?.ToLower() ?? "en";

        if (!Translations.ContainsKey(lang))
        {
            lang = "en";
        }

        if (Translations[lang].TryGetValue(key, out var value))
        {
            return value;
        }

        if (lang != "en" && Translations["en"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }
}
